# Generated by Django 5.0 on 2024-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SilverSwan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='plugin_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
